# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://jstools.dev/eslint-config/

root: true
extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended', 'plugin:mocha/recommended']
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint', "eslint-plugin-mocha"]

